POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "fullName": "kwame Osei",
    "email": "kyeisamuel9@gmail.com",
    "password": "rexosei111"
}
###
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "fullName": "Test User 2",
    "email": "testUser2@gmail.com",
    "password": "testuser",
    "profile": {
        "dob": "2001-05-06",
        "education": [{
            "school": {
                "name": "University of Mines"
            },
            "degree": "Bsc. Computer Science",
            "fieldOfStudy": "Computer Science",
            "startDate": "2019-09-02",
            "grade": 83
        }],
        "unicoyn": 21

    }
}

###
POST http://localhost:5000/api/auth/oauth
Content-Type: application/json
X-Auth-Provider: GOOGLE

{
   "fullName": "Name Name",
   "picture": "http://localhost",
    "email": "oduro22@gmail.com",
    "authProvider": "GOOGLE"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
   "email": "rexosei111@gmail.com",
   "password": "rexosei111"
}

###

POST http://localhost:5000/api/auth/authProvider
Content-Type: application/json

{
    "email": "kyeisamuel931@gmail.com"
}

###

GET http://localhost:5000/api/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0NTA1MDM3OSwiZXhwIjoxNjQ1MDUwOTc5fQ.nEH88Ssh_uE0Lnriig2aoCpZJY-sQTKT7hNcfP8TMBo

###

PATCH http://localhost:5000/api/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJEY2hvbGVAZ21haWwuY29tIiwiaXNzIjoidW5pdHVtOnBsYXRmb3JtIiwiaWF0IjoxNjQ0MTYxMjgwLCJleHAiOjE2NDQxNjE4ODB9.kEPgvDILhObc6tjLAVYWty6XwTBTcoObQI3AkHyN6Ds

{
   "profile": {    
    "picture": "https://liel2c.deta.dev/images/BTa8GQJQJV6VXdmFyqpDCc.png",
    "education": {
        "school": {
            "name": "University of Mines",
            "url": "http://localhost:3000/sja"
        }
    }
   } 
}

###

GET http://localhost:5000/api/users/me/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0NDE1MDYyNCwiZXhwIjoxNjQ0MTUxMjI0fQ.37bsATrjioFC8NfOBGp4gYlWs-cSEnpTAZUVLuoyCbQ
###
GET http://localhost:5000/api/users/me/communities
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJvaGVuZXNldHd1bWFzaUBnbWFpbC5jb20iLCJpc3MiOiJ1bml0dW06cGxhdGZvcm0iLCJpYXQiOjE2NDM4NDY3NzYsImV4cCI6MTY0Mzg0NzM3Nn0.nm4ITHTwgDBU6tdy_iBPRIgMsxjJIqdPPckr1A019ZA
###

###
POST http://localhost:5000/api/users/me/schoolWork
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0NDE5NDI1OCwiZXhwIjoxNjQ0MTk0ODU4fQ.XjNii3eS5hNpdCYuh6oX8ITkg341m11N_PyjN9yEXZ0

{
    "title": "New School Work 23",
    "description": "Meaninful",
    "grade": "79",
    "media": ["http://localhost:5000/images"]
}

###

PATCH  http://localhost:5000/api/users/me/schoolWork/61f3ee24f010c823c0c38a99
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0MzQ1NzA3OCwiZXhwIjoxNjQzNDU3Njc4fQ.p_SoNWWeV1fjbPJ6mN-scvEZ4ej9X9qi920NLEozpm8

{
    "title": "New Work",
    "description": "sjfsdkjfsiowj",
    "grade": "89"
}

###

DELETE http://localhost:5000/api/users/me/schoolWork/61f3ee24f010c823c0c38a99
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0MzQ1NzA3OCwiZXhwIjoxNjQzNDU3Njc4fQ.p_SoNWWeV1fjbPJ6mN-scvEZ4ej9X9qi920NLEozpm8

###
GET http://localhost:5000/api/auth/token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0MjI5MzM3MywiZXhwIjoxNjQyODk4MTczfQ._SvnyzCDK-omh4kL4qepkum9F0yh4PNHKah68sXr354"
}

###

GET http://localhost:5000/api/search/?post=1&search=n
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0Mzc3MTkwNCwiZXhwIjoxNjQzNzcyNTA0fQ.LHN7U_XHLTsJWh8b8Gt9lRpXf855mkDU_xmSA3EZuYE
###

POST http://localhost:5000/api/community/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0NDk2NDg1NSwiZXhwIjoxNjQ0OTY1NDU1fQ.txekPDwilFi_TYo-xJxVnRGTUG7ALC-3M7vjvO4mFek

{
    "name": "Javascript",
    "description": "All about JS"
}

###

POST http://localhost:5000/api/community/620036d7f5ddd13572603ee2/join HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0NDIyOTQzMiwiZXhwIjoxNjQ0MjMwMDMyfQ.qVXeUBEiuOKPgjsbuHQBaXablJvC5-aXqyB1wacJdBI

###
GET http://localhost:5000/api/community/620036d7f5ddd13572603ee2/requests HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0NDk2NDg1NSwiZXhwIjoxNjQ0OTY1NDU1fQ.txekPDwilFi_TYo-xJxVnRGTUG7ALC-3M7vjvO4mFek

###
PATCH http://localhost:5000/api/community/62012198a708a6f13627af32
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0NTA0NTY5MiwiZXhwIjoxNjQ1MDQ2MjkyfQ.5jBgWWQA5buWeoww6fEB_lkDPetq7nMffytEWcNwEJU

{
    "name": "Typescript v4",
    "description": "Latest channel on the tube"
}

###
DELETE http://localhost:5000/api/community/620c278379621e47f847cbff
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0NDk2NDg1NSwiZXhwIjoxNjQ0OTY1NDU1fQ.txekPDwilFi_TYo-xJxVnRGTUG7ALC-3M7vjvO4mFek

###

GET http://localhost:5000/api/community/62012198a708a6f13627af32/members/?skip=0&limit=2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0NTA0ODA3MiwiZXhwIjoxNjQ1MDQ4NjcyfQ.SX-_tng4vFEq2XUUATkapXjy-bmqoltzVivZm4u6-fU


###
GET http://localhost:5000/api/community/?search=channel1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0MzEyMDcwMiwiZXhwIjoxNjQzMTIxMzAyfQ.xSqpNJpajgC-Sn709VVpreTVNnm8aa8JaKK7sNRyWzU

###
GET http://localhost:5000/api/community/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0NTA0NTAxNiwiZXhwIjoxNjQ1MDQ1NjE2fQ.PsBByiqsiyOsLJuH53qlAwgEbSmiBetgWpXu0mHhFzc

###
GET http://localhost:5000/api/community/posts HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJEY2hvbGVAZ21haWwuY29tIiwiaXNzIjoidW5pdHVtOnBsYXRmb3JtIiwiaWF0IjoxNjQ0MTc0ODAxLCJleHAiOjE2NDQxNzU0MDF9.73vNmwU62_hEvFpYUhwAmWS9Wl0qPRwnuZEnohrD0mA

###
GET http://localhost:5000/api/community/62012198a708a6f13627af32 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0NTA0NTY5MiwiZXhwIjoxNjQ1MDQ2MjkyfQ.5jBgWWQA5buWeoww6fEB_lkDPetq7nMffytEWcNwEJU

###

POST http://localhost:5000/api/community/62012198a708a6f13627af32/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0NTA0NzM5OSwiZXhwIjoxNjQ1MDQ3OTk5fQ.beZCUiLoSUskb-QsO0jc6Htn9DzzAvvAURn3iUC7sNk

{
    "userID": "62012198a708a6f13627af25"
}
###

DELETE http://localhost:5000/api/community/61f6c5e9322b64a993b1e956/remove
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0MzU2NDQ4MiwiZXhwIjoxNjQzNTY1MDgyfQ.JDAzvIzrZSqd5wOmre2whOIIosaaPbosfxFInDcL8-4

{
    "userID": "61f671741c9134d46565f333"
}

###
DELETE http://localhost:5000/api/community/61f6c5e9322b64a993b1e956/leave
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0MzQ1NzA3OCwiZXhwIjoxNjQzNDU3Njc4fQ.p_SoNWWeV1fjbPJ6mN-scvEZ4ej9X9qi920NLEozpm8

###
POST http://localhost:5000/api/users/me/education
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJEY2hvbGVAZ21haWwuY29tIiwiaXNzIjoidW5pdHVtOnBsYXRmb3JtIiwiaWF0IjoxNjQ0MTEyMTk4LCJleHAiOjE2NDQxMTI3OTh9.LqxVet6HIzgftrcHWTQkpG4erq0ky1aXLB3RIaHzpQ0

{
    "school": {
        "name": "University of Mines"
    },
    "degree": "Bsc. Computer Science",
    "fieldOfStudy": "Computer Science",
    "startDate": "2019-09-02",
    "grade": 83
}

###
PATCH http://localhost:5000/api/users/me/education/61f6c24e49b30163d4ee90f8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0Mzc1ODU0OSwiZXhwIjoxNjQzNzU5MTQ5fQ.1s8Lil0Pb7Im1Nr77L0SJRTlwxL34WSkN9KpcZ-l3D0

{
    "degree": "Bsc. Mechanical"
}
###
DELETE http://localhost:5000/api/users/me/education/61f6c24e49b30163d4ee90f8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0Mzc1ODU0OSwiZXhwIjoxNjQzNzU5MTQ5fQ.1s8Lil0Pb7Im1Nr77L0SJRTlwxL34WSkN9KpcZ-l3D0
###

GET http://localhost:5000/api/users/me/education/61f6c24e49b30163d4ee90f8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0Mzc1ODU0OSwiZXhwIjoxNjQzNzU5MTQ5fQ.1s8Lil0Pb7Im1Nr77L0SJRTlwxL34WSkN9KpcZ-l3D0
###
GET http://localhost:5000/api/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0MjA4MzQ3NCwiZXhwIjoxNjQyMDg0MDc0fQ.ZQB3xHPHQazlkICyqvinN7KeyV_1pDecloaIuNiGzGE

###
GET http://localhost:5000/api/users/me/savedPosts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0Mzc1ODU0OSwiZXhwIjoxNjQzNzU5MTQ5fQ.1s8Lil0Pb7Im1Nr77L0SJRTlwxL34WSkN9KpcZ-l3D0

###
POST http://localhost:5000/api/users/me/savedPosts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0NDExMDk5OCwiZXhwIjoxNjQ0MTExNTk4fQ.-wfIfzNpYPwOwoS3OUKJfwcahs6XGxCSucNJM2OGR4s

{
    "postID": "61ff1d37102af04a498c5a02"
}
###

DELETE http://localhost:5000/api/users/me/savedPosts/61f9c0a888d2e1f9a67f1633
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0Mzc1ODU0OSwiZXhwIjoxNjQzNzU5MTQ5fQ.1s8Lil0Pb7Im1Nr77L0SJRTlwxL34WSkN9KpcZ-l3D0

###
GET http://localhost:5000/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0NTA1MDM3OSwiZXhwIjoxNjQ1MDUwOTc5fQ.nEH88Ssh_uE0Lnriig2aoCpZJY-sQTKT7hNcfP8TMBo

###

POST http://localhost:5000/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJEY2hvbGVAZ21haWwuY29tIiwiaXNzIjoidW5pdHVtOnBsYXRmb3JtIiwiaWF0IjoxNjQ0MjM4NTEzLCJleHAiOjE2NDQyMzkxMTN9.JjMm4NiDdPp8f6fG0tDmssCi1333w3OVzkw8O2mzHdE

{
    "body": "Cloud Computing 2",
    "communityID": "61ffd5e38d00c9c40047eec2"
}

###

PATCH http://localhost:5000/api/posts/61e548336a7bd80d43e3f79f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0MjQxODQ3NCwiZXhwIjoxNjQyNDE5MDc0fQ.hn78LL0K6-sFz5S-g6uaEOg2G4KpvmHluz0hfjhAC04

{
    "body": "This is the first post for testing"
}

####

GET http://localhost:5000/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0NTA1MDM3OSwiZXhwIjoxNjQ1MDUwOTc5fQ.nEH88Ssh_uE0Lnriig2aoCpZJY-sQTKT7hNcfP8TMBo

###

GET http://localhost:5000/api/posts/61ff1d37102af04a498c5a02
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0NDE1MDYyNCwiZXhwIjoxNjQ0MTUxMjI0fQ.37bsATrjioFC8NfOBGp4gYlWs-cSEnpTAZUVLuoyCbQ

###

DELETE http://localhost:5000/api/posts/61e548336a7bd80d43e3f79f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0MjQxODQ3NCwiZXhwIjoxNjQyNDE5MDc0fQ.hn78LL0K6-sFz5S-g6uaEOg2G4KpvmHluz0hfjhAC04

###
POST http://localhost:5000/api/posts/61fec19dec8561a74843be25/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0NDEwMzI2NywiZXhwIjoxNjQ0MTAzODY3fQ.qwjY5JQfDP0-2ra7AzG6NtYMK_MEIf-TarC1moKtlbM

{
    "text": "I like this post"
}

###

GET http://localhost:5000/api/posts/61fec19dec8561a74843be25/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0NDEwMzI2NywiZXhwIjoxNjQ0MTAzODY3fQ.qwjY5JQfDP0-2ra7AzG6NtYMK_MEIf-TarC1moKtlbM

###

DELETE http://localhost:5000/api/posts/comments/61e56aa53b5e6cb86dda0a3c
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0MjQyNzEyMiwiZXhwIjoxNjQyNDI3NzIyfQ.UB6zDkP1qh99fxin61f5Bwr7DOAxTbwhC4WXP52j-R0

###

PATCH http://localhost:5000/api/posts/61ff1d37102af04a498c5a02/upvote
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJEY2hvbGVAZ21haWwuY29tIiwiaXNzIjoidW5pdHVtOnBsYXRmb3JtIiwiaWF0IjoxNjQ0MTUyMjgxLCJleHAiOjE2NDQxNTI4ODF9.RmqMZ5qn2LUNMFB4cVVXtWL2xrXHfeQqznQyVGfidMo

###

PATCH http://localhost:5000/api/posts/61f96f3d3ac6fda9e2d53704/downvote
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0MzgxMTQyMywiZXhwIjoxNjQzODEyMDIzfQ.X7jXPGQb0tC8rQu4mn0IBcCvdhRhLTHLsQR6YMwZiT0

###
POST http://localhost:5000/api/contact
Content-Type: application/json

{
    "email": "kyeisamuel931@gmail.com",
    "name": "Kyei Samuel",
    "message": "Hi, Broke Boys😁😂"
}