POST http://unitum-api-dev.us-east-1.elasticbeanstalk.com/api/auth/register
Content-Type: application/json

{
    "fullName": "kwame Osei",
    "email": "kyeisamuel9@gmail.com",
    "password": "rexosei111"
}
###
POST http://unitum-api-dev.us-east-1.elasticbeanstalk.com/api/auth/register
Content-Type: application/json

{
    "fullName": "Test User 2",
    "email": "testUser2@gmail.com",
    "password": "testuser",
    "profile": {
        "dob": "2001-05-06",
        "education": [{
            "school": {
                "name": "University of Mines"
            },
            "degree": "Bsc. Computer Science",
            "fieldOfStudy": "Computer Science",
            "startDate": "2019-09-02",
            "grade": 83
        }],
        "unicoyn": 21

    }
}

###
POST http://unitum-api-dev.us-east-1.elasticbeanstalk.com/api/auth/oauth
Content-Type: application/json
X-Auth-Provider: GOOGLE

{
   "fullName": "Name Name",
   "picture": "http://localhost",
    "email": "oduro22@gmail.com",
    "authProvider": "GOOGLE"
}

###
POST http://unitum-api-dev.us-east-1.elasticbeanstalk.com/api/auth/login
Content-Type: application/json

{
   "email": "john@example.com",
   "password": "123456"

}

###

POST http://unitum-api-dev.us-east-1.elasticbeanstalk.com/api/auth/authProvider
Content-Type: application/json

{
    "email": "kyeisamuel931@gmail.com"
}

###

GET http://unitum-api-dev.us-east-1.elasticbeanstalk.com/api/users/me
Content-Type: application/json

Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY1Njg1ODc2NywiZXhwIjoxNjU2ODU5MzY3fQ.7RWmIcrxCMuMrAxyDyVZKrfNa6tlr7jIgRMTqiyFFM8


###
POST http://unitum-api-dev.us-east-1.elasticbeanstalk.com/api/users/me/follow/625021be74f7349176886eb0
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY1Njg1NzY4MSwiZXhwIjoxNjU2ODU4MjgxfQ.QUQSAIBOAGYQn-S0qXQ2TvtVnX1QLltZJDjx8LdBrWs


###
PATCH http://unitum-api-dev.us-east-1.elasticbeanstalk.com/api/users/me/unfollow/625021be74f7349176886eb0
Content-Type: application/json
Authorization: Bearer yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY1Njg1NzM2OSwiZXhwIjoxNjU2ODU3OTY5fQ.20BPNXRC_rxM5ICG4wRtwnmuFWsCTXLnzprQGJRZ3xA

###
PATCH http://unitum-api-dev.us-east-1.elasticbeanstalk.com/api/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqb2huQGV4YW1wbGUuY29tIiwiaXNzIjoidW5pdHVtOnBsYXRmb3JtIiwiaWF0IjoxNjQ4NzI1OTYyLCJleHAiOjE2NDg3MjY1NjJ9.xLviWlH-6sZ8JjW_0Yxu-bl5cceDw65bSbHwAshSXM0

{
   "profile": {
    "education": {
        "school": {
            "name": "University of Mines",
            "url": "http://localhost:3000/sja"
        },
        "fieldOfStudy": "Computer Science and Engineering",
        "startDate": "2019-04-08"
    }
   } 
}

###

GET http://unitum-api-dev.us-east-1.elasticbeanstalk.com/api/users/me/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY1Njg1NzU1MSwiZXhwIjoxNjU2ODU4MTUxfQ.p3a6O4onFnq8o1cEkBttM3lsIK_Vx7NKGPlWUQWCkbQ
###
GET http://unitum-api-dev.us-east-1.elasticbeanstalk.com/api/users/me/communities
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJvaGVuZXNldHd1bWFzaUBnbWFpbC5jb20iLCJpc3MiOiJ1bml0dW06cGxhdGZvcm0iLCJpYXQiOjE2NDM4NDY3NzYsImV4cCI6MTY0Mzg0NzM3Nn0.nm4ITHTwgDBU6tdy_iBPRIgMsxjJIqdPPckr1A019ZA
###

###
POST http://unitum-api-dev.us-east-1.elasticbeanstalk.com/api/users/me/schoolWork
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0NDE5NDI1OCwiZXhwIjoxNjQ0MTk0ODU4fQ.XjNii3eS5hNpdCYuh6oX8ITkg341m11N_PyjN9yEXZ0

{
    "title": "New School Work 23",
    "description": "Meaninful",
    "grade": "79",
    "media": ["http://unitum-api-dev.us-east-1.elasticbeanstalk.com/images"]
}

###

PATCH  http://unitum-api-dev.us-east-1.elasticbeanstalk.com/api/users/me/schoolWork/61f3ee24f010c823c0c38a99
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0MzQ1NzA3OCwiZXhwIjoxNjQzNDU3Njc4fQ.p_SoNWWeV1fjbPJ6mN-scvEZ4ej9X9qi920NLEozpm8

{
    "title": "New Work",
    "description": "sjfsdkjfsiowj",
    "grade": "89"
}

###

DELETE http://unitum-api-dev.us-east-1.elasticbeanstalk.com/api/users/me/schoolWork/61f3ee24f010c823c0c38a99
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0MzQ1NzA3OCwiZXhwIjoxNjQzNDU3Njc4fQ.p_SoNWWeV1fjbPJ6mN-scvEZ4ej9X9qi920NLEozpm8

###
GET http://unitum-api-dev.us-east-1.elasticbeanstalk.com/api/auth/token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0NTE3Njk3OSwiZXhwIjoxNjQ1NzgxNzc5fQ.fpH9DxMxoIqKB30_RBlmtPQ4lrrbOdyeDxbzSIjOMds"
}

###

GET http://unitum-api-dev.us-east-1.elasticbeanstalk.com/api/search/?post=1&search=n
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0Mzc3MTkwNCwiZXhwIjoxNjQzNzcyNTA0fQ.LHN7U_XHLTsJWh8b8Gt9lRpXf855mkDU_xmSA3EZuYE
###

POST http://unitum-api-dev.us-east-1.elasticbeanstalk.com/api/community/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0NDk2NDg1NSwiZXhwIjoxNjQ0OTY1NDU1fQ.txekPDwilFi_TYo-xJxVnRGTUG7ALC-3M7vjvO4mFek

{
    "name": "Javascript",
    "description": "All about JS"
}

###

POST http://unitum-api-dev.us-east-1.elasticbeanstalk.com/api/community/62134a52b4eb26767db2d2a4/join HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJEY2hvbGVAZ21haWwuY29tIiwiaXNzIjoidW5pdHVtOnBsYXRmb3JtIiwiaWF0IjoxNjQ3NzI2NzMzLCJleHAiOjE2NDc3MjczMzN9.lVdSJ8hfzbRkh4qem4f2ly9f17u7_ir1ETVNgBy5wtw

###
GET http://unitum-api-dev.us-east-1.elasticbeanstalk.com/api/community/62134a52b4eb26767db2d2a4/requests HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0NzcyNjk1NSwiZXhwIjoxNjQ3NzI3NTU1fQ.7ZGUbCZTScvbYlSIMVr23Hwaj_mA8M5xgdAJpog57nI

###
PATCH http://unitum-api-dev.us-east-1.elasticbeanstalk.com/api/community/62012198a708a6f13627af32
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0NTA0NTY5MiwiZXhwIjoxNjQ1MDQ2MjkyfQ.5jBgWWQA5buWeoww6fEB_lkDPetq7nMffytEWcNwEJU

{
    "name": "Typescript v4",
    "description": "Latest channel on the tube"
}

###
DELETE http://unitum-api-dev.us-east-1.elasticbeanstalk.com/api/community/620c278379621e47f847cbff
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0NDk2NDg1NSwiZXhwIjoxNjQ0OTY1NDU1fQ.txekPDwilFi_TYo-xJxVnRGTUG7ALC-3M7vjvO4mFek

###

GET http://unitum-api-dev.us-east-1.elasticbeanstalk.com/api/community/62012198a708a6f13627af32/members/?skip=0&limit=2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0NTA0ODA3MiwiZXhwIjoxNjQ1MDQ4NjcyfQ.SX-_tng4vFEq2XUUATkapXjy-bmqoltzVivZm4u6-fU


###
GET http://unitum-api-dev.us-east-1.elasticbeanstalk.com/api/community/?search=channel1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0MzEyMDcwMiwiZXhwIjoxNjQzMTIxMzAyfQ.xSqpNJpajgC-Sn709VVpreTVNnm8aa8JaKK7sNRyWzU

###
GET http://unitum-api-dev.us-east-1.elasticbeanstalk.com/api/community/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0NTA0NTAxNiwiZXhwIjoxNjQ1MDQ1NjE2fQ.PsBByiqsiyOsLJuH53qlAwgEbSmiBetgWpXu0mHhFzc

###
GET http://unitum-api-dev.us-east-1.elasticbeanstalk.com/api/community/posts HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJEY2hvbGVAZ21haWwuY29tIiwiaXNzIjoidW5pdHVtOnBsYXRmb3JtIiwiaWF0IjoxNjQ0MTc0ODAxLCJleHAiOjE2NDQxNzU0MDF9.73vNmwU62_hEvFpYUhwAmWS9Wl0qPRwnuZEnohrD0mA

###
GET http://unitum-api-dev.us-east-1.elasticbeanstalk.com/api/community/62012198a708a6f13627af32 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0NTA0NTY5MiwiZXhwIjoxNjQ1MDQ2MjkyfQ.5jBgWWQA5buWeoww6fEB_lkDPetq7nMffytEWcNwEJU

###

POST http://unitum-api-dev.us-east-1.elasticbeanstalk.com/api/community/62012198a708a6f13627af32/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0NTA0NzM5OSwiZXhwIjoxNjQ1MDQ3OTk5fQ.beZCUiLoSUskb-QsO0jc6Htn9DzzAvvAURn3iUC7sNk

{
    "userID": "62012198a708a6f13627af25"
}
###

DELETE http://unitum-api-dev.us-east-1.elasticbeanstalk.com/api/community/61f6c5e9322b64a993b1e956/remove
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0MzU2NDQ4MiwiZXhwIjoxNjQzNTY1MDgyfQ.JDAzvIzrZSqd5wOmre2whOIIosaaPbosfxFInDcL8-4

{
    "userID": "61f671741c9134d46565f333"
}

###
DELETE http://unitum-api-dev.us-east-1.elasticbeanstalk.com/api/community/61f6c5e9322b64a993b1e956/leave
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0MzQ1NzA3OCwiZXhwIjoxNjQzNDU3Njc4fQ.p_SoNWWeV1fjbPJ6mN-scvEZ4ej9X9qi920NLEozpm8

###
POST http://unitum-api-dev.us-east-1.elasticbeanstalk.com/api/users/me/education
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJEY2hvbGVAZ21haWwuY29tIiwiaXNzIjoidW5pdHVtOnBsYXRmb3JtIiwiaWF0IjoxNjQ0MTEyMTk4LCJleHAiOjE2NDQxMTI3OTh9.LqxVet6HIzgftrcHWTQkpG4erq0ky1aXLB3RIaHzpQ0

{
    "school": {
        "name": "University of Mines"
    },
    "degree": "Bsc. Computer Science",
    "fieldOfStudy": "Computer Science",
    "startDate": "2019-09-02",
    "grade": 83
}

###
PATCH http://unitum-api-dev.us-east-1.elasticbeanstalk.com/api/users/me/education/61f6c24e49b30163d4ee90f8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0Mzc1ODU0OSwiZXhwIjoxNjQzNzU5MTQ5fQ.1s8Lil0Pb7Im1Nr77L0SJRTlwxL34WSkN9KpcZ-l3D0

{
    "degree": "Bsc. Mechanical"
}
###
DELETE http://unitum-api-dev.us-east-1.elasticbeanstalk.com/api/users/me/education/61f6c24e49b30163d4ee90f8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0Mzc1ODU0OSwiZXhwIjoxNjQzNzU5MTQ5fQ.1s8Lil0Pb7Im1Nr77L0SJRTlwxL34WSkN9KpcZ-l3D0
###

GET http://unitum-api-dev.us-east-1.elasticbeanstalk.com/api/users/me/education/61f6c24e49b30163d4ee90f8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0Mzc1ODU0OSwiZXhwIjoxNjQzNzU5MTQ5fQ.1s8Lil0Pb7Im1Nr77L0SJRTlwxL34WSkN9KpcZ-l3D0
###
GET http://unitum-api-dev.us-east-1.elasticbeanstalk.com/api/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0MjA4MzQ3NCwiZXhwIjoxNjQyMDg0MDc0fQ.ZQB3xHPHQazlkICyqvinN7KeyV_1pDecloaIuNiGzGE

###
GET http://unitum-api-dev.us-east-1.elasticbeanstalk.com/api/users/me/savedPosts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0Mzc1ODU0OSwiZXhwIjoxNjQzNzU5MTQ5fQ.1s8Lil0Pb7Im1Nr77L0SJRTlwxL34WSkN9KpcZ-l3D0

###
POST http://unitum-api-dev.us-east-1.elasticbeanstalk.com/api/users/me/savedPosts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0NDExMDk5OCwiZXhwIjoxNjQ0MTExNTk4fQ.-wfIfzNpYPwOwoS3OUKJfwcahs6XGxCSucNJM2OGR4s

{
    "postID": "61ff1d37102af04a498c5a02"
}
###

DELETE http://unitum-api-dev.us-east-1.elasticbeanstalk.com/api/users/me/savedPosts/61f9c0a888d2e1f9a67f1633
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0Mzc1ODU0OSwiZXhwIjoxNjQzNzU5MTQ5fQ.1s8Lil0Pb7Im1Nr77L0SJRTlwxL34WSkN9KpcZ-l3D0

###
GET http://unitum-api-dev.us-east-1.elasticbeanstalk.com/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJreWVpc2FtdWVsOUBnbWFpbC5jb20iLCJpc3MiOiJ1bml0dW06cGxhdGZvcm0iLCJpYXQiOjE2NDg1MTg0MTgsImV4cCI6MTY0ODUxOTAxOH0.YEO6GhiFliLpBkf9rRimH6KqPFyxNvleTADR_Ic_9dg
###

POST http://unitum-api-dev.us-east-1.elasticbeanstalk.com/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJEY2hvbGVAZ21haWwuY29tIiwiaXNzIjoidW5pdHVtOnBsYXRmb3JtIiwiaWF0IjoxNjQ0MjM4NTEzLCJleHAiOjE2NDQyMzkxMTN9.JjMm4NiDdPp8f6fG0tDmssCi1333w3OVzkw8O2mzHdE

{
    "body": "Cloud Computing 2",
    "communityID": "61ffd5e38d00c9c40047eec2"
}

###

PATCH http://unitum-api-dev.us-east-1.elasticbeanstalk.com/api/posts/61e548336a7bd80d43e3f79f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJreWVpc2FtdWVsOUBnbWFpbC5jb20iLCJpc3MiOiJ1bml0dW06cGxhdGZvcm0iLCJpYXQiOjE2NDg1MTg0MTgsImV4cCI6MTY0ODUxOTAxOH0.YEO6GhiFliLpBkf9rRimH6KqPFyxNvleTADR_Ic_9dg
{
    "body": "This is the first post for testing"
}

####

GET http://unitum-api-dev.us-east-1.elasticbeanstalk.com/api/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0NTA1MDM3OSwiZXhwIjoxNjQ1MDUwOTc5fQ.nEH88Ssh_uE0Lnriig2aoCpZJY-sQTKT7hNcfP8TMBo

###

GET http://unitum-api-dev.us-east-1.elasticbeanstalk.com/api/posts/62363becfaee5fade9da038a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJreWVpc2FtdWVsOUBnbWFpbC5jb20iLCJpc3MiOiJ1bml0dW06cGxhdGZvcm0iLCJpYXQiOjE2NDg1MTg0MTgsImV4cCI6MTY0ODUxOTAxOH0.YEO6GhiFliLpBkf9rRimH6KqPFyxNvleTADR_Ic_9dg
###

DELETE http://unitum-api-dev.us-east-1.elasticbeanstalk.com/api/posts/61e548336a7bd80d43e3f79f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0MjQxODQ3NCwiZXhwIjoxNjQyNDE5MDc0fQ.hn78LL0K6-sFz5S-g6uaEOg2G4KpvmHluz0hfjhAC04

###
POST http://unitum-api-dev.us-east-1.elasticbeanstalk.com/api/posts/61fec19dec8561a74843be25/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0NDEwMzI2NywiZXhwIjoxNjQ0MTAzODY3fQ.qwjY5JQfDP0-2ra7AzG6NtYMK_MEIf-TarC1moKtlbM

{
    "text": "I like this post"
}

###

GET http://unitum-api-dev.us-east-1.elasticbeanstalk.com/api/posts/61fec19dec8561a74843be25/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0NDEwMzI2NywiZXhwIjoxNjQ0MTAzODY3fQ.qwjY5JQfDP0-2ra7AzG6NtYMK_MEIf-TarC1moKtlbM

###

DELETE http://unitum-api-dev.us-east-1.elasticbeanstalk.com/api/posts/comments/61e56aa53b5e6cb86dda0a3c
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0MjQyNzEyMiwiZXhwIjoxNjQyNDI3NzIyfQ.UB6zDkP1qh99fxin61f5Bwr7DOAxTbwhC4WXP52j-R0

###

PATCH http://unitum-api-dev.us-east-1.elasticbeanstalk.com/api/posts/61ff1d37102af04a498c5a02/upvote
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJEY2hvbGVAZ21haWwuY29tIiwiaXNzIjoidW5pdHVtOnBsYXRmb3JtIiwiaWF0IjoxNjQ0MTUyMjgxLCJleHAiOjE2NDQxNTI4ODF9.RmqMZ5qn2LUNMFB4cVVXtWL2xrXHfeQqznQyVGfidMo

###

PATCH http://unitum-api-dev.us-east-1.elasticbeanstalk.com/api/posts/61f96f3d3ac6fda9e2d53704/downvote
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0MzgxMTQyMywiZXhwIjoxNjQzODEyMDIzfQ.X7jXPGQb0tC8rQu4mn0IBcCvdhRhLTHLsQR6YMwZiT0

###
POST http://unitum-api-dev.us-east-1.elasticbeanstalk.com/api/contact
Content-Type: application/json

{
    "email": "kyeisamuel931@gmail.com",
    "name": "Kyei Samuel",
    "message": "Hi, Broke Boys😁😂"
}

###

GET http://unitum-api-dev.us-east-1.elasticbeanstalk.com/api/chat
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0NjQ2ODMzMCwiZXhwIjoxNjQ2NDY4OTMwfQ.IPIZ4Bu9U7XvJVjSQr3WOqV2hTe6yiw0x7RNbQn_X-4

###

POST http://unitum-api-dev.us-east-1.elasticbeanstalk.com/api/chat/new
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0NjQ2NzYwOSwiZXhwIjoxNjQ2NDY4MjA5fQ.tLXMt9Z2Q1OpnCoXtMxWfZjVrpOIthe9z2COLcr3NYY

{
    "to": "62138c2a340560118a8d923a",
    "text": "Yo Barnes"
}
###
POST http://unitum-api-dev.us-east-1.elasticbeanstalk.com/api/chat/62134a54b4eb26767db2d2b5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0NTQzOTU4OSwiZXhwIjoxNjQ1NDQwMTg5fQ.rphPI3hsC-mNOcjW8LK3E2JzaE2Gvv6c479wv3hhtYY

{
    "text": "Hi Bunny"
}

###
GET http://unitum-api-dev.us-east-1.elasticbeanstalk.com/api/chat/62134a54b4eb26767db2d2b5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJyZXhvc2VpMTExQGdtYWlsLmNvbSIsImlzcyI6InVuaXR1bTpwbGF0Zm9ybSIsImlhdCI6MTY0NjQ2ODMzMCwiZXhwIjoxNjQ2NDY4OTMwfQ.IPIZ4Bu9U7XvJVjSQr3WOqV2hTe6yiw0x7RNbQn_X-4
