POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "firstname": "Kyei",
    "lastname": "Samuel",
    "otherNames": "Osei",
    "email": "kyeisamuel931@gmail.com",
    "password": "rexosei111"
}

###
POST http://localhost:3000/api/auth/oauth
Content-Type: application/json
X-Auth-Provider: GOOGLE

{
    "given_name": "Barnes",
    "family_name": "Oduro",
    "otherNames": "Twumasi",
    "email": "oduro123@gmail.com",
    "authProvider": "GOOGLE"
}

###
POST  http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "kyeisamuel931@gmail.com",
    "password": "rexosei111"
}

###

POST http://localhost:3000/api/auth/authProvider
Content-Type: application/json

{
    "email": "kyeisamuel931@gmail.com"
}

###